Repository Pavan-Kamthane/Cpp_Lang, pull requests merged in 2022-10, with the labels that each got.

#2 some c++ programs
  ArrayPassByReference.exe
  palindrom.exe
  subArrayOfArray.exe
  subArraySumMax.exe
Labels: hacaktoberfest, hacaktoberfest-accepted

#3 Matrix multiplication
  Matrix
Labels: hacaktoberfest, hacaktoberfest-accepted

#4 hacktoberfest2022
  nvfijdnfb
Labels: hacaktoberfest, hacaktoberfest-accepted

#5 Create lcs.cpp
  lcs.cpp
Labels: hacaktoberfest, hacaktoberfest-accepted

#6 Hacktoberfest
  C++.12cpp
Labels: hacaktoberfest, hacaktoberfest-accepted

#7 merge sort.cpp
  README.md
  merge sort .cpp
Labels: hacaktoberfest, hacaktoberfest-accepted

#8 Factorial program in c++
  factorial.cpp
Labels: hacaktoberfest, hacaktoberfest-accepted

#9 Hactoberfest2022
  Pyramid.cpp
Labels: hacaktoberfest, hacaktoberfest-accepted

#10 Binary Serach Program using C++
  Binary_Seach.cpp
Labels: hacaktoberfest, hacaktoberfest-accepted

#11 Create Transposeofmatrix.cpp
  Transposeofmatrix.cpp
Labels: hacaktoberfest, hacaktoberfest-accepted

#12 calculator
  calculator.cpp
Labels: hacaktoberfest, hacaktoberfest-accepted

#21 Hacktoberfest2022
  c++team.cpp
Labels: hacaktoberfest, hacaktoberfest-accepted

#20 Adding oddeven sort algorithm in cpp
  oddevensort.cpp
Labels: hacaktoberfest, hacaktoberfest-accepted

#19 Hacktoberfest2022
  star pattern.cpp
Labels: hacaktoberfest, hacaktoberfest-accepted

#18 hacktoberfest2022
  31aug8.cpp
Labels: hacaktoberfest, hacaktoberfest-accepted

#17 pattern.cpp
  pattern.cpp
Labels: hacaktoberfest, hacaktoberfest-accepted

#16 hacktoberfest2022
  sortArray.cpp
Labels: hacaktoberfest, hacaktoberfest-accepted

#15 Hello world
  hello.cpp
Labels: hacaktoberfest, hacaktoberfest-accepted

#14 hacktoberfest2022
  Matrix_Transpose.cpp
Labels: hacaktoberfest, hacaktoberfest-accepted

#24 Create Bubble sort in cpp
  Bubble sort in cpp
Labels: hacaktoberfest, hacaktoberfest-accepted

#25 Cpp code for Fibonacci series
  Fibonacci.cpp
Labels: hacaktoberfest, hacaktoberfest-accepted

#23 hacktoberfest2022
  gv.c++
  practice4.c
Labels: hacaktoberfest, hacaktoberfest-accepted

#22 hacktoberfest2022
  Saria afreen.cpp
Labels: hacaktoberfest, hacaktoberfest-accepted

#31 file into folder
  Binary Seach/Binary_Seach.cpp
  Bubble sort/Bubble_sort.cpp
  Fibonacci.cpp
  Guess the Number/guess_the_number.cpp
  Hello world/hello.cpp
  Hello world/hello_world.cpp
  Matrix-Transpose/Matrix_Transpose.cpp
  Matrix-Transpose/Transposeofmatrix.cpp
  Matrix/Matrix.cpp
  Pyramid/Pyramid.cpp
  Structure/structure.cpp
  calculator/calculator.cpp
  constructor & destructor/constroctor_and_destructor.cpp
  factorial/factorial.cpp
  factorial/factorial2.cpp
  fibonacci series/fibonacci_series.cpp
  gv.c++
  lcs/lcs.cpp
  merge sort/merge_sort.cpp
  oddevensort/oddevensort.cpp
  pattern/pattern.cpp
  practice/practice4.c
  sortArray/sortArray.cpp
  star pattern/star_pattern.cpp
  structure-python/structure.py
Labels: hacaktoberfest, hacaktoberfest-accepted

#27 Prime and Swap in C++
  prime.cpp
  swap.cpp
Labels: hacaktoberfest, hacaktoberfest-accepted

#32 functionoverload
  athul/functionoverload.cpp
Labels: hacaktoberfest, hacaktoberfest-accepted

#34 Create quicksort in cpp
  quicksort.cpp
Labels: hacaktoberfest, hacaktoberfest-accepted

#36 Travelling salesman problem
  tsp.cpp
Labels: hacaktoberfest, hacaktoberfest-accepted

#37 hacktoberfest2022
  stackimplementation.cpp
Labels: hacaktoberfest, hacaktoberfest-accepted

#38 Create Krishnangshu Paul
  Krishnangshu Paul
Labels: hacaktoberfest, hacaktoberfest-accepted

#39 Create matrix_tranpose.cpp
  matrix_tranpose.cpp
Labels: hacaktoberfest, hacaktoberfest-accepted

#13 factorial
  factorial.cpp
Labels: hacaktoberfest, hacaktoberfest-accepted

#35 timeclock.cpp
  Timeclock.cpp
Labels: hacaktoberfest, hacaktoberfest-accepted

#41 Create linear_search.cpp
  linear_search.cpp
Labels: hacaktoberfest, hacaktoberfest-accepted

#44 Reverse_prefix
  Reverse_prefix
Labels: hacaktoberfest, hacaktoberfest-accepted

#46 Stock
  122BestTimeBuyandSell2.cpp
Labels: hacaktoberfest, hacaktoberfest-accepted

#48 hactoberfest2022
  bubble_sort.cpp
Labels: hacaktoberfest, hacaktoberfest-accepted

#49 added HCF/GCD program in Cpp
  GCD.cpp
Labels: hacaktoberfest, hacaktoberfest-accepted

#51 added code for some questions of recursion and linked list
  Linked List/CircularLL.cpp
  Linked List/CircularLL.exe
  Linked List/DoublyLL.cpp
  Linked List/DoublyLL.exe
  Linked List/SingleLL.cpp
  Linked List/SingleLL.exe
  Recursion/.vscode/settings.json
  Recursion/PalindromeString.cpp
  Recursion/PalindromeString.exe
  Recursion/countSubseq.cpp
  Recursion/countSubseq.exe
  Recursion/factorial.cpp
  Recursion/factorial.exe
  Recursion/fibonacci.cpp
  Recursion/fibonacci.exe
  Recursion/print1ToN.cpp
  Recursion/print1ToN.exe
  Recursion/print1ToNBacktracking.cpp
  Recursion/print1ToNBacktracking.exe
  Recursion/printNTo1.cpp
  Recursion/printNTo1.exe
  Recursion/printNTo1BackTracking.cpp
  Recursion/printNTo1BackTracking.exe
  Recursion/printNameNTimes.cpp
  Recursion/printNameNTimes.exe
  Recursion/printSubseqOfGivenSum.cpp
  Recursion/printSubseqOfGivenSum.exe
  Recursion/printSubsequence.cpp
  Recursion/printSubsequence.exe
  Recursion/reverseArray.cpp
  Recursion/reverseArray.exe
  Recursion/sumOfFirstNNumber.cpp
  Recursion/sumOfFirstNNumber.exe
Labels: hacaktoberfest, hacaktoberfest-accepted

#50 hacktoberfest2022
  binarytodecimal.cpp
Labels: hacaktoberfest, hacaktoberfest-accepted

#52 added chef and array cpp code
  chef_and_array.cpp
Labels: hacaktoberfest, hacaktoberfest-accepted

#53 First_Code_of_Cpp
  firstcode_of_Cpp
Labels: hacaktoberfest, hacaktoberfest-accepted

#45 Create dnf-sort.cpp
  dnf-sort.cpp
Labels: hacaktoberfest, hacaktoberfest-accepted

#54 added friend function basic c++ program
  friend-func.cpp
Labels: hacaktoberfest, hacaktoberfest-accepted

#55 Circular linked list of dsa in c++ in added
  DSA in CPP/Linked List/linked_list_ circular.cpp
Labels: hacaktoberfest, hacaktoberfest-accepted

#56 added binarytree program
  binary-tree.cpp
Labels: hacaktoberfest, hacaktoberfest-accepted

#60 leap year.cpp
  leap year.cpp
Labels: hacaktoberfest, hacaktoberfest-accepted

#59 Create warshall.cpp
  warshall.cpp
Labels: hacaktoberfest, hacktoberfest-accepted

#58 numpy
  numpy
Labels: hacaktoberfest, hacktoberfest-accepted

#57 Added Kruskals MCST Algorithm
  Greedy Algorithms/Kruskals_MCST.cpp
Labels: hacktoberfest-accepted

#64 Created Adult or not.cpp
  Varun Kotgire/Adult or not.cpp
Labels: hacaktoberfest, hacktoberfest-accepted

#65 Created c++ program
  Varad Chandrawar/class.c++
Labels: hacaktoberfest, hacktoberfest-accepted

#63 Checks prime number
  CheckPrime.cpp
Labels: hacaktoberfest, hacktoberfest-accepted

#62 Binary Search
  BinarySearch.cpp
Labels: hacaktoberfest, hacktoberfest-accepted

#66 hacktoberfest2022
  kaveri7989
Labels: hacaktoberfest, hacktoberfest-accepted

#67 file into folder #part 2
  ArrayPassByReference.exe
  Arrays/chef_and_array.cpp
  Arrays/numpy.cpp
  Bubble sort/bubble-sort.cpp
  Bubble sort/bubble_sort.cpp
  GCD/GCD.cpp
  Hello world/firstcode.Cpp
  Matrix-Transpose/matrix_tranpose.cpp
  Matrix/Krishnangshu_Paul.cpp
  Prefix/Reverse_prefix.cpp
  README.md
  Timeclock/Timeclock.cpp
  binary tree/binary-tree.cpp
  binarytodecimal/binarytodecimal.cpp
  buy & sell/122BestTimeBuyandSell2.cpp
  factorial/factorial3.cpp
  functions/friend-func.cpp
  functions/warshall.cpp
  heapSort/heapSort.cpp
  linear & binary search/linear_search.cpp
  palindrom.exe
  prime/prime.cpp
  quicksort/quicksort.cpp
  sort/dnf-sort.cpp
  stackimplementation/stackimplementation.cpp
  subArrayOfArray.exe
  subArraySumMax.exe
  swap/swap.cpp
  travelling salesman prblm/tsp.cpp
  year/leap_year.cpp
Labels: hacaktoberfest, hacktoberfest-accepted

#68 Create Beautiful_matrix(Codeforces).cpp
  Arrays/Beautiful_matrix(Codeforces).cpp
Labels: hacaktoberfest, hacktoberfest-accepted

#69 Create binarytree_delete_node.cpp
  binary tree/binarytree_delete_node.cpp
Labels: hacaktoberfest, hacktoberfest-accepted

#70 Create bubblesort.cpp
  bubblesort.cpp
Labels: hacaktoberfest, hacktoberfest-accepted

#79 Reverse of an array
  Arrays/ReverseArray
Labels: hacaktoberfest, hacaktoberfest-accepted, hacktoberfest-accepted

#78 Create dnf_sort.cpp
  dnf_sort.cpp
Labels: hacaktoberfest, hacaktoberfest-accepted, hacktoberfest-accepted

#81 roots in cpp and Convert File into Folder
  Bubble sort/bubblesort.cpp
  factorial/factorial4.cpp
  linear & binary search/BinarySearch.cpp
  prime/CheckPrime.cpp
  roots/roots.cpp
Labels: hacaktoberfest, hacktoberfest-accepted

#80 Hacktoberfest22
  Any 2.cpp
Labels: hacaktoberfest, hacktoberfest-accepted

#77 Create matrix_multiplication.cpp
  matrix_multiplication.cpp
Labels: hacaktoberfest, hacktoberfest-accepted

#73 hactoberfest2022
  b.java
Labels: hacaktoberfest, hacktoberfest-accepted

#74 hactoberfest2022
  c.java
Labels: hacaktoberfest, hacktoberfest-accepted

#75 Created Auti29.cpp
  Auti29.cpp
Labels: hacaktoberfest, hacktoberfest-accepted

#72 Hacktoberfest2022
  Loops/Factorial.cpp
  factorial/palindrome.cpp
Labels: hacaktoberfest, hacktoberfest-accepted

#71 Binary search program added
  Binary_search.cpp
Labels: hacktoberfest-accepted

#76 nested_loop_in_Cpp_language
  nested_loop_in_cpp
Labels: hacktoberfest-accepted

#82 Create triangle.cpp
  triangle.cpp
Labels: hacaktoberfest, hacaktoberfest-accepted, hacktoberfest-accepted

#83 jayantchaudhari18 -added this file.Hacktoerfest.please merge.
  jayantchaudhari18.cpp
Labels: hacaktoberfest, hacaktoberfest-accepted, hacktoberfest-accepted

#84 Hacktoberfest2022
  divyansh44.cpp
Labels: hacaktoberfest, hacktoberfest-accepted

#85 68 programs for begginers
  68 small basic programs
Labels: hacaktoberfest, hacaktoberfest-accepted, hacktoberfest-accepted

#92 files organised
  Binary Seach/Binary_search.cpp
  Loops/nested_loop_in_cpp
  Matrix/matrix_multiplication.cpp
Labels: hacaktoberfest, hacaktoberfest-accepted, hacktoberfest-accepted

#91 hacktoberfest2022
  mustafa.cpp
Labels: hacaktoberfest, hacaktoberfest-accepted, hacktoberfest-accepted

#90 Hacktoberfest2022
  Hacktoberfest2022.cpp
Labels: hacaktoberfest, hacaktoberfest-accepted, hacktoberfest-accepted

#89 Cpp_Recursion
  Cpp_Recursion
  Cpp_pointers
Labels: hacaktoberfest, hacaktoberfest-accepted, hacktoberfest-accepted

#88 Added Longest Common Subsequence (LCS) program
  Dynamic Programming/Longest_Increasing_Subsequence.cpp
Labels: hacaktoberfest, hacaktoberfest-accepted, hacktoberfest-accepted

#87 hacktoberfest2022
  garvit128729.cpp
Labels: hacaktoberfest, hacaktoberfest-accepted, hacktoberfest-accepted

#95 Create array.cpp
  array.cpp
  palindrome.cpp
Labels: hacaktoberfest, hacaktoberfest-accepted, hacktoberfest-accepted

#93 added the heap question findClosetElements
  Vijay/findkCLosetElements.cpp
Labels: hacaktoberfest, hacaktoberfest-accepted, hacktoberfest-accepted

#94 hacktoberfest2022
  vm.cpp
Labels: hacaktoberfest-accepted, hacktoberfest-accepted

#86 Create Cycle Sort.cpp
  Cycle Sort.cpp
Labels: hacaktoberfest, hacaktoberfest-accepted, hacktoberfest-accepted

#96 Created EvenOrOd.cpp
  EvenOrOdd.cpp
Labels: hacaktoberfest, hacaktoberfest-accepted, hacktoberfest-accepted

#97 Tic Tac Toe in C++
  tictactoe.cpp
Labels: hacaktoberfest, hacaktoberfest-accepted, hacktoberfest-accepted

#98 next_permutation added
  Arrays/next_permutation.cpp
Labels: hacaktoberfest, hacaktoberfest-accepted, hacktoberfest-accepted

#106 hacktoberfest2022
  Linked List/insert-at-beginning-of-singlylinkedlist.cpp
Labels: hacktoberfest-accepted

#99 same_tree added
  Arrays/same_tree.cpp
Labels: hacktoberfest-accepted

#105 Create transpose_matrix.cpp
  transpose.cpp
Labels: hacktoberfest-accepted

#104 Added Reverse Linked List Program
  Linked List/Reverse_Linked_List.cpp
Labels: hacktoberfest-accepted

#103 AddTwoNumber
  Nancy/AddTwoNumber.cpp
Labels: hacktoberfest-accepted

#102 Find-K-Closest-Element
  Bubble sort/bubble_sort.cpp
  Rohan/Find-K-Closest-Element.cpp
Labels: hacktoberfest-accepted

#100 Hacktoberfest2022
  Sorting.cpp
Labels: hacktoberfest-accepted

#107 Function overloading
  Function overloading
Labels: hacktoberfest-accepted

#108 hacktoberfest2022
  c++
Labels: hacktoberfest-accepted

#109 hactoberfest2022
  factorial.cpp
Labels: hacktoberfest-accepted

#113 Cpp_Boolean
  Cpp_Boolean
Labels: hacktoberfest-accepted

#112 Hacktoberfest2022
  Cellpadding And Cellspacing Attributes.txt
Labels: hacktoberfest-accepted

#111 Hacktoberfest2022
  Csorting.cpp
Labels: hacktoberfest-accepted

#110 Hacktoberfest2022
  attendance.txt
Labels: hacktoberfest-accepted

#115 hacktobefest2022
  pascaltriangle.cpp
Labels: hacktoberfest-accepted

#116 fibonacii number using dp
  Dynamic Programming/fibonacii number using dp.cpp
Labels: hacktoberfest-accepted

#117 binary_search_with _recursion
  Binary Seach/binary_search_with _recursion.cpp
Labels: hacktoberfest-accepted

#118 added binary_search_using_while_loop(iteration)
  Binary Seach/binary_search_using_while_loop(iteration).cpp
Labels: hacktoberfest-accepted

#114 sudokuSolver
  sudokuSolver.cpp
Labels: hacktoberfest-accepted

#119 hacktobfest2022
  add_distance.cpp
Labels: hacaktoberfest, hacaktoberfest-accepted, hacktoberfest-accepted

#122 CPP code
  calculator - Copy (2)/calculator.cpp
  calculator - Copy/calculator.cpp
  factorial.cpp
  function.cpp
Labels: hacaktoberfest, hacaktoberfest-accepted, hacktoberfest-accepted

#120 hacktobefest2022
  transpose_matrix.cpp
Labels: hacaktoberfest, hacaktoberfest-accepted, hacktoberfest-accepted

#121 display_user_input_string_pattern
  Increase_String_font.cpp
  Increase_String_font.exe
Labels: hacaktoberfest, hacaktoberfest-accepted, hacktoberfest-accepted

#123 Basic operation on array
  Array_operation.cpp
  Array_operation.exe
Labels: hacktoberfest-accepted

#124 Create mergeSort.cpp
  sort/mergeSort.cpp
Labels: hacktoberfest-accepted

#125 Create ExchangeFirstLast.cpp
  DSA in CPP/Linked List/ExchangeFirstLast.cpp
Labels: hacktoberfest-accepted

#126 Create pythagoras triplet
  pythagoras_triplet.cpp
Labels: hacktoberfest-accepted

#129 hacktoberfest
  java code 1
Labels: hacktoberfest-accepted

#127 hacktoberfest
  code2
Labels: hacktoberfest-accepted

#128 (hacktoberfest2022)Create selectionsort.cpp
  Sorting/selectionsort.cpp
Labels: hacktoberfest-accepted

#130 hacktoberfest Create mycode5
  mycode5
Labels: hacktoberfest-accepted

#131 hacktoerfest Create 51code.java
  51code.java
Labels: hacktoberfest-accepted

#133 hacktoberfest Create Check Palindrome String
  Check Palindrome String
Labels: hacktoberfest-accepted

#134 Hacktoberfest2022
  Pattern.cpp
Labels: hacktoberfest-accepted

#135 Matrix Multiplication.cpp
  Matrix/Matrix Multiplication.cpp
Labels: hacktoberfest-accepted

#136 Hacktoberfest2022
  practical7.txt
Labels: hacaktoberfest, hacaktoberfest-accepted, hacktoberfest-accepted

#138 add merge sort
  Sorting/mergeSort.cpp
Labels: hacktoberfest-accepted

#153 Find subsequence of integer for a given sum.
  Shivam_Mishra/Find_Subsequence.cpp
Labels: hacktoberfest-accepted

#152 Create height of tree in c++
  Arrays/height of tree in c++
Labels: hacktoberfest-accepted

#140 Hactoberfest2k22
  Clock.cpp
Labels: hacktoberfest-accepted

#141 Create Stopwatch.cpp
  Stopwatch.cpp
Labels: hacktoberfest-accepted

#142 Made a Simple Calculator using C++
  simple calculator.cpp
Labels: hacktoberfest-accepted

#144 Create Simple C++ program
  Kunal/Simple C++ program
Labels: hacktoberfest-accepted

#145 add linear probing and binary tree
  Hashing/linearprobing.cpp
  Hello world/hellothere.cpp
  bintree.cpp
Labels: hacktoberfest-accepted

#146 Create clock.cpp
  digital_watch/clock.cpp
Labels: hacktoberfest-accepted

#147 Create mergesort.cpp
  mergesort.cpp
Labels: hacktoberfest-accepted

#151 HeartPattern.cpp
  Heartpattern.cpp
Labels: hacktoberfest-accepted

#150 RealPyramid.cpp
  RealPyramid.cpp
Labels: hacktoberfest-accepted

#148 Butterfly.cpp
  Butterfly.cpp
Labels: hacktoberfest-accepted

#149 FibonacciRecursion.cpp
  FibonacciRecursion.cpp
Labels: hacktoberfest-accepted

#154 Add Combination Formula
  Apoorva/RecursiveCombinationFormula.cpp
Labels: hacktoberfest-accepted

#155 Juggling Algorithm
  Juggling_Algorithm/Juggling.cpp
Labels: hacktoberfest-accepted

#156 Invert_pyramid Pattern
  Invert_pyramid.cpp
Labels: hacktoberfest-accepted

#157 added a c code for rock paper scissor
  rock_paper_scissors.c
Labels: hacktoberfest-accepted

#158 Update Binary_Seach.cpp
  Binary Seach/Binary_Seach.cpp
Labels: hacktoberfest-accepted

#161 Added swapping method
  Dipankar/a.exe
  Dipankar/swap_without_third_variable.cpp
Labels: hacktoberfest-accepted

#175 Nth node from end of linked list
  Arushi_Agarwal/Nth node from end of linked list
Labels: hacktoberfest-accepted

#174 Segregate even and odd nodes in a Link List
  Arushi_CPP/Segregate even and odd nodes in a Link List
Labels: hacktoberfest-accepted

#173 Hacktoberfest2022
  Hcf.cpp
Labels: hacktoberfest-accepted

#172 linked list code added
  KHUSHI
Labels: hacktoberfest-accepted

#171 hacktoberfest Create c6
  c6
Labels: hacktoberfest-accepted

#170 Leetcode 2181. Merge Nodes Between Zeros
  Leetcode/2181MergeNodesBetweenZeros.cpp
Labels: hacktoberfest-accepted

#168 Leetcode 2095. Delete the Middle Node
  Leetcode/2095DeleteMiddleNodeLL.cpp
Labels: hacktoberfest-accepted
